In [1]:
import numpy as np

In [2]:
np.array([8,4,6,0,2])

array([8, 4, 6, 0, 2])

In [3]:
print(np.array([1,3,5,7,9]))

[1 3 5 7 9]


In [4]:
# Create a 2*1 array
A = np.array( [[1,2,3],[4,5,6]] )

In [5]:
print(A)

[[1 2 3]
 [4 5 6]]


In [6]:
# Print entries (1,2) and (2,3)
print(A[0,1],A[1,2])

2 6


In [7]:
A[0]

array([1, 2, 3])

In [8]:
# Problem 1
A = np.array( [[3,-1,4],[1,5,-9]] )
B = np.array( [[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]] )

In [9]:
# Dot product of matrices A and B
A@B

In [11]:
np.dot(A,B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [12]:
# Concatenate two lists together (note they are not arrays!)
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [13]:
[1,2,3] * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [15]:
x,y = np.array([1,2,3]),np.array([4,5,6])

In [16]:
x + 10

array([11, 12, 13])

In [17]:
x * 4

array([ 4,  8, 12])

In [18]:
x + y

array([5, 7, 9])

In [19]:
# Component-wise multiplication
x * y

array([ 4, 10, 18])

In [25]:
# Problem 2
A = np.array([[3,1,4],[1,5,9],[-5,3,1]])
-A@A@A + 9*A@A - 15*A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.ones((2,5), dtype=np.int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
I = np.eye(2)

In [29]:
np.full_like(I,3)

array([[3., 3.],
       [3., 3.]])

In [30]:
x = np.array([0,1,2,3,4])
x = x.astype(np.float64)

In [33]:
x.dtype

dtype('float64')

In [34]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [36]:
np.diag(A)

array([1, 5, 9])

In [37]:
np.diag([1,11,111])

array([[  1,   0,   0],
       [  0,  11,   0],
       [  0,   0, 111]])

In [52]:
# Problem 3
A = np.ones((7,7))
A = np.triu(A)
B = np.ones((7,7)) * 5
C = np.ones((7,7)) * -6
C = np.tril(C)       
B = B + C
D = A@B@A
D = D.astype(np.float64)
print(D)

[[ -7.  -8.  -3.   8.  25.  48.  77.]
 [ -6. -12. -12.  -6.   6.  24.  48.]
 [ -5. -10. -15. -14.  -7.   6.  25.]
 [ -4.  -8. -12. -16. -14.  -6.   8.]
 [ -3.  -6.  -9. -12. -15. -12.  -3.]
 [ -2.  -4.  -6.  -8. -10. -12.  -8.]
 [ -1.  -2.  -3.  -4.  -5.  -6.  -7.]]


In [54]:
x = np.arange(10)

In [57]:
x[:3] # everything up to 3
x[3:] # everything from 3 onward

array([3, 4, 5, 6, 7, 8, 9])

In [58]:
x[3:8] # everything from 3 to 8, not including 8

array([3, 4, 5, 6, 7])

In [59]:
A = np.array([[0,1,2,3,4],[5,6,7,8,9]])
A[1,2] # the (2,3) entry of the matrix

array([[2, 3, 4],
       [7, 8, 9]])

In [61]:
A[:,2:] # the submatrix from the 3rd column onward

array([[2, 3, 4],
       [7, 8, 9]])

In [63]:
x = np.arange(0,50,10)
index = np.array([3,1,4])
x[index]

array([30, 10, 40])

In [65]:
y = np.arange(10,20,2)
mask = y > 15
y[mask]

array([16, 18])

In [68]:
# Problem 4
def select_negative(m):
    idx = m < 0
    n = m[idx]
    return n

x = np.array([[-1,2],[3,-5]])
select_negative(x)

array([-1, -5])

In [71]:
A = np.arange(12).reshape((3,-1))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
np.ravel(A)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
A.T # transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [74]:
A = np.arange(6).reshape((2,3))
B = np.zeros((4,3))
np.vstack((A,B,A))

array([[0., 1., 2.],
       [3., 4., 5.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 2.],
       [3., 4., 5.]])

In [75]:
A = A.T
B = np.ones((3,4))
np.hstack((A,B,A))

array([[0., 3., 1., 1., 1., 1., 0., 3.],
       [1., 4., 1., 1., 1., 1., 1., 4.],
       [2., 5., 1., 1., 1., 1., 2., 5.]])

In [77]:
np.column_stack((A,np.zeros(3),np.ones(3),np.full(3,2)))

array([[0., 3., 0., 1., 2.],
       [1., 4., 0., 1., 2.],
       [2., 5., 0., 1., 2.]])

In [106]:
# Problem 5
A = np.array([[0,2,4],[1,3,5]])
B = np.array([[3,0,0],[3,3,0],[3,3,3]])
C = -2 * np.array([[1,1,1]])
C = np.diag(C)

D = np.hstack((np.full_like(A.T,0),A.T,np.eye(A.shape[1])))
E = np.hstack((A,np.zeros([A.shape[0],A.T.shape[1]]),np.zeros([A.shape[0],A.T.shape[1]])))
F = np.vstack((D,E))
print(F)

[[0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 2. 3. 0. 1. 0.]
 [0. 0. 4. 5. 0. 0. 1.]
 [0. 2. 4. 0. 0. 0. 0.]
 [1. 3. 5. 0. 0. 0. 0.]]


In [103]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [107]:
x = np.arange(3)
y = np.arange(0,40,10).reshape((4,1))
x + y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])